# Generated by Django 4.2.14 on 2024-09-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_location_objectkes_alter_reportdgu_dgu_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='object_kes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.objectkes'),
        ),
    ]
