# Generated by Django 4.2.14 on 2024-09-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_createdgu_object_kes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createdgu',
            options={'verbose_name': 'ДГУ', 'verbose_name_plural': 'ДГУ'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участок'},
        ),
        migrations.AlterModelOptions(
            name='objectkes',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объект'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Пост'},
        ),
        migrations.AddField(
            model_name='location',
            name='object_kes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.objectkes'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Номер Дгу'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='object_kes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.objectkes', verbose_name='Обьект'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='power',
            field=models.IntegerField(verbose_name='Мощьность КВт'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
