# Generated by Django 4.2.14 on 2024-09-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_createdgu_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectkes',
            old_name='address',
            new_name='manager',
        ),
    ]
