# Generated by Django 4.2.14 on 2024-09-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_address_objectkes_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdgu',
            name='object_kes',
        ),
        migrations.AddField(
            model_name='createdgu',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.location', verbose_name='Обьект'),
        ),
    ]
