# Generated by Django 4.2.14 on 2024-09-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_createdgu_object_kes_createdgu_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVSmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_dvs', models.CharField(max_length=30, verbose_name='Модель ДВС')),
                ('power', models.IntegerField(blank=True, verbose_name='Мощьность ДВС')),
                ('volume', models.IntegerField(blank=True, verbose_name='Объем ДВС')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ДВС',
                'verbose_name_plural': 'Модель ДВС',
            },
        ),
        migrations.AlterModelOptions(
            name='reportdgu',
            options={'verbose_name': 'Ежедневный отчет', 'verbose_name_plural': 'Ежедневный отчет'},
        ),
        migrations.RemoveField(
            model_name='createdgu',
            name='power',
        ),
        migrations.AddField(
            model_name='createdgu',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='dgu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.createdgu', verbose_name='Номер Дгу'),
        ),
        migrations.CreateModel(
            name='DVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=50, verbose_name='ДВС')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('model_dvs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.dvsmodel', verbose_name='Модель ДВС')),
            ],
            options={
                'verbose_name': 'ДВС',
                'verbose_name_plural': 'ДВС',
            },
        ),
        migrations.AddField(
            model_name='createdgu',
            name='dvs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.dvs', verbose_name='Модель ДВС'),
        ),
    ]
