# Generated by Django 4.2.14 on 2024-09-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_dvsmodel_cylinders_alter_dvsmodel_model_dvs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvsmodel',
            name='volume',
        ),
    ]
