# Generated by Django 4.2.14 on 2024-09-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_dvs_engine_hours_alter_dvs_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производитель',
            },
        ),
        migrations.AddField(
            model_name='dvsmodel',
            name='maker_dvs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.maker', verbose_name='Производитель'),
        ),
    ]
