# Generated by Django 4.2.14 on 2024-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_maker_dvsmodel_maker_dvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdgu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
