# Generated by Django 4.2.14 on 2024-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_reportdgu_time_create_reportdgu_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvsmodel',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объем ДВС'),
        ),
    ]
