# Generated by Django 4.2.14 on 2024-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_reportdgu_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectkes',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
