# Generated by Django 4.2.14 on 2024-10-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0015_objectkes_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectkes',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_obj', to=settings.AUTH_USER_MODEL),
        ),
    ]
