# Generated by Django 4.2.14 on 2024-10-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_objectkes_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.AddField(
            model_name='createdgu',
            name='paralel',
            field=models.BooleanField(default=False, verbose_name='Паралель'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='work',
            field=models.BooleanField(default=False, verbose_name='вРаботе'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.status', verbose_name='Состояние'),
        ),
    ]
