# Generated by Django 4.2.14 on 2024-10-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_status_createdgu_paralel_createdgu_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='dmasla',
            field=models.BooleanField(default=True, verbose_name='Давление масла'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='l1',
            field=models.BooleanField(default=True, verbose_name='L1'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='l2',
            field=models.BooleanField(default=True, verbose_name='L2'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='l3',
            field=models.BooleanField(default=True, verbose_name='L3'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='nagruzka',
            field=models.BooleanField(default=True, verbose_name='Нагрузка'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='narabotka',
            field=models.BooleanField(default=True, verbose_name='Наработка'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='primechanie',
            field=models.BooleanField(default=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='tog',
            field=models.BooleanField(default=True, verbose_name='Темп. Охл. Жидкости'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='work',
            field=models.BooleanField(default=False, verbose_name='в Работе'),
        ),
    ]
