# Generated by Django 4.2.14 on 2024-10-20 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0018_createdgu_dmasla_createdgu_l1_createdgu_l2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='operator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_area', to=settings.AUTH_USER_MODEL),
        ),
    ]
