# Generated by Django 4.2.14 on 2024-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_location_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная Нагрузка'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='akb',
            field=models.BooleanField(default=True, verbose_name='АКБ'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='full_load',
            field=models.BooleanField(default=True, verbose_name='Полная  Нагрузка'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='reactive',
            field=models.BooleanField(default=True, verbose_name='Реактивная  Нагрузка'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='active',
            field=models.PositiveIntegerField(default=True, verbose_name='Активная Нагрузка'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='akb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='АКБ'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='dmasla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Давление масла'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='full_load',
            field=models.PositiveIntegerField(default=True, verbose_name='Полная  Нагрузка'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='l1',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='L1'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='l2',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='L2'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='l3',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='L3'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='nagruzka',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Нагрузка'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='narabotka',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Наработка'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='reactive',
            field=models.PositiveIntegerField(default=True, verbose_name='Реактивная  Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='tc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Темп. Охл. Жидкости'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Замечания'),
        ),
    ]
