# Generated by Django 4.2.14 on 2024-10-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_createdgu_active_createdgu_akb_createdgu_full_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdgu',
            name='active',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Активная Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='full_load',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Полная  Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='l1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='L1'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='l2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='L2'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='l3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='L3'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='nagruzka',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='narabotka',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='reactive',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Реактивная  Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Замечания'),
        ),
    ]
