# Generated by Django 4.2.14 on 2024-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_alter_reportdgu_active_alter_reportdgu_akb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdgu',
            name='title',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='Замечания'),
        ),
    ]
