# Generated by Django 4.2.14 on 2024-11-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_alter_reportdgu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='long_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Название Дгу'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='post_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.post', verbose_name='Название поста'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='dvs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.dvs', verbose_name='ДВС'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание  проблем'),
        ),
        migrations.AlterField(
            model_name='dvs',
            name='sn',
            field=models.CharField(blank=True, max_length=70, verbose_name='Серейный номер'),
        ),
        migrations.CreateModel(
            name='AlternatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_alternator', models.CharField(blank=True, max_length=30, verbose_name='Модель ДВС')),
                ('power_res_kva', models.IntegerField(blank=True, verbose_name='Мощьность Резервная кВа')),
                ('power_res_kvt', models.IntegerField(blank=True, verbose_name='Мощьность Резервная кВт')),
                ('power_rab_kva', models.IntegerField(blank=True, verbose_name='Мощьность Основная кВа')),
                ('power_rab_kvt', models.IntegerField(blank=True, verbose_name='Мощьность Основная кВт')),
                ('diod_most', models.CharField(blank=True, max_length=30, verbose_name='Диодный мост')),
                ('diodes_1', models.CharField(blank=True, max_length=30, verbose_name='Диод 1')),
                ('diodes_2', models.CharField(blank=True, max_length=30, verbose_name='Диод 2')),
                ('varistor', models.CharField(blank=True, max_length=30, verbose_name='Варистор')),
                ('resistor', models.CharField(blank=True, max_length=30, verbose_name='Резистор')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('maker_alternator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.maker', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель Генератора',
                'verbose_name_plural': 'Модель Генератора',
            },
        ),
        migrations.CreateModel(
            name='Alternator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=70, verbose_name='Серейный номер')),
                ('hours_alternator', models.IntegerField(blank=True, verbose_name='Моточасы')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Описание')),
                ('model_alternator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.alternatormodel', verbose_name='Модель ДВС')),
            ],
            options={
                'verbose_name': 'Генератор',
                'verbose_name_plural': 'Герератор',
            },
        ),
    ]
