# Generated by Django 4.2.14 on 2024-11-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_createdgu_long_name_createdgu_post_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='alternator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.alternator', verbose_name='ДВС'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='dvs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.dvs', verbose_name='ДВС'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.location', verbose_name='Обьект'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='long_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название Дгу'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='post_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.post', verbose_name='Название поста'),
        ),
    ]
