# Generated by Django 4.2.14 on 2024-11-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_createdgu_alternator_alter_createdgu_dvs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='koguch',
            field=models.BooleanField(default=False, verbose_name='Кожухное Исполнение'),
        ),
        migrations.AlterField(
            model_name='alternator',
            name='model_alternator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.alternatormodel', verbose_name='Генератор'),
        ),
        migrations.AlterField(
            model_name='alternatormodel',
            name='model_alternator',
            field=models.CharField(blank=True, max_length=30, verbose_name='Модель Генератора'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='alternator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.alternator', verbose_name='Генератор'),
        ),
        migrations.AlterField(
            model_name='dvs',
            name='model_dvs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.dvsmodel', verbose_name='ДВС'),
        ),
    ]
