# Generated by Django 4.2.14 on 2024-11-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_createdgu_koguch_alter_alternator_model_alternator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='maker_dvs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.maker', verbose_name='Производитель'),
        ),
    ]
