# Generated by Django 4.2.14 on 2024-12-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_alternatormodel_weight_createdgu_lsh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternator',
            name='model_alternator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.alternatormodel', verbose_name='Генератор'),
        ),
        migrations.AlterField(
            model_name='dvs',
            name='model_dvs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.dvsmodel', verbose_name='ДВС'),
        ),
    ]
