# Generated by Django 4.2.14 on 2024-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_createdgu_data_to_createdgu_interval_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdgu',
            name='data_to',
            field=models.DateTimeField(blank=True, default='2024-09-25 06:00', null=True, verbose_name='Дата последнего ТО'),
        ),
    ]
