# Generated by Django 4.2.14 on 2024-12-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_alter_createdgu_data_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdgu',
            name='maker_dvs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.maker', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='active',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Активная Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='akb',
            field=models.FloatField(blank=True, null=True, verbose_name='АКБ'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='dmasla',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление масла'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='full_load',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Полная  Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='l1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='L1'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='l2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='L2'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='l3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='L3'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='nagruzka',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='narabotka',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='reactive',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Реактивная  Нагрузка'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='tc',
            field=models.FloatField(blank=True, null=True, verbose_name='Темп. Охл. Жидкости'),
        ),
    ]
