# Generated by Django 4.2.14 on 2024-12-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_alter_createdgu_maker_dvs_alter_reportdgu_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdgu',
            name='data_to',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Дата последнего ТО'),
        ),
    ]
