# Generated by Django 4.2.14 on 2024-12-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_alter_createdgu_data_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternator',
            name='hours_alternator',
            field=models.FloatField(blank=True, null=True, verbose_name='Моточасы'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='data_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО'),
        ),
        migrations.AlterField(
            model_name='dvs',
            name='engine_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Моточасы'),
        ),
        migrations.AlterField(
            model_name='reportdgu',
            name='narabotka',
            field=models.FloatField(blank=True, null=True, verbose_name='Наработка'),
        ),
    ]
