# Generated by Django 4.2.14 on 2024-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_alter_createdgu_data_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdgu',
            name='data_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО'),
        ),
    ]
