# Generated by Django 4.2.14 on 2024-12-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_alter_alternator_hours_alternator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emkost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер емкости')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примичание')),
                ('meter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Измерения см.')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.location', verbose_name='Название локации')),
            ],
            options={
                'verbose_name': 'Емкость',
                'verbose_name_plural': 'Емкость',
            },
        ),
        migrations.CreateModel(
            name='EmkostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название емкости')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примичание')),
                ('volume', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объем  л.')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Вес пустой кг')),
                ('lsh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длинна * Ширина * Высота ')),
            ],
            options={
                'verbose_name': 'Модель Емкости',
                'verbose_name_plural': 'Модель Емкости',
            },
        ),
        migrations.CreateModel(
            name='TKModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название Контейнера')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примичание')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Вес пустого Контейнера кг')),
                ('lsh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длинна * Ширина * Высота ')),
            ],
            options={
                'verbose_name': 'Модель ТК',
                'verbose_name_plural': 'Модель ТК',
            },
        ),
        migrations.CreateModel(
            name='TK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер емкости')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примичание')),
                ('emkost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.emkost', verbose_name='Емкость')),
                ('model_tk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.tkmodel', verbose_name='Название Контейнера')),
            ],
            options={
                'verbose_name': 'ТК',
                'verbose_name_plural': 'ТК',
            },
        ),
        migrations.AddField(
            model_name='emkost',
            name='model_em',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.emkostmodel', verbose_name='Название емкости'),
        ),
        migrations.AddField(
            model_name='emkost',
            name='post_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.post', verbose_name='Название поста'),
        ),
    ]
