# Generated by Django 4.2.14 on 2024-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0035_emkost_emkostmodel_tkmodel_tk_emkost_model_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emkost',
            name='meter',
            field=models.FloatField(blank=True, null=True, verbose_name='Измерения см.'),
        ),
    ]
