# Generated by Django 4.2.14 on 2024-12-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_alter_createdgu_data_to'),
        ('report', '0036_alter_emkost_meter'),
    ]

    operations = [
    ]
