# Generated by Django 4.2.14 on 2024-12-14 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_merge_20241208_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emkost',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер емкости'),
        ),
        migrations.AlterField(
            model_name='emkostmodel',
            name='lsh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Длинна * Ширина * Высота '),
        ),
        migrations.AlterField(
            model_name='emkostmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название емкости'),
        ),
        migrations.AlterField(
            model_name='tk',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер емкости'),
        ),
        migrations.AlterField(
            model_name='tkmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Контейнера'),
        ),
        migrations.CreateModel(
            name='Pump_meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер насоса')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примичание')),
                ('meter', models.FloatField(blank=True, default=0, null=True, verbose_name='Покозания счетчика насоса')),
                ('meter1', models.FloatField(blank=True, default=0, null=True, verbose_name='Покозания счетчика насоса короткое')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.location', verbose_name='Название локации')),
                ('post_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.post', verbose_name='Название поста')),
            ],
            options={
                'verbose_name': 'Номер насоса',
                'verbose_name_plural': 'Номер насоса',
            },
        ),
        migrations.CreateModel(
            name='Mercury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер Счетчика')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примичание')),
                ('meter', models.FloatField(blank=True, default=0, null=True, verbose_name='Покозания Меркурия')),
                ('meter1', models.FloatField(blank=True, default=0, null=True, verbose_name='Покозания Меркурия короткое')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.location', verbose_name='Название локации')),
                ('post_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.post', verbose_name='Название поста')),
            ],
            options={
                'verbose_name': 'Mercury',
                'verbose_name_plural': 'Mercury',
            },
        ),
    ]
