# Generated by Django 4.2.14 on 2024-12-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0038_alter_emkost_number_alter_emkostmodel_lsh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercury',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mercury',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='pump_meter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pump_meter',
            name='post_name',
        ),
        migrations.AddField(
            model_name='createdgu',
            name='emkost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.emkost', verbose_name='Номер емкости'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='frequency',
            field=models.BooleanField(default=True, verbose_name='Частота'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='mercury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.mercury', verbose_name='Счетчик меркурий'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='tk',
            field=models.BooleanField(default=True, verbose_name='ТК'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='voltage',
            field=models.BooleanField(default=True, verbose_name='Напряжение'),
        ),
        migrations.AddField(
            model_name='pump_meter',
            name='emkost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.emkost', verbose_name='Емкость'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Напряжение'),
        ),
    ]
