# Generated by Django 4.2.14 on 2024-12-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0039_remove_mercury_location_remove_mercury_post_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump_meter',
            name='emkost',
        ),
        migrations.AddField(
            model_name='emkost',
            name='pitat',
            field=models.BooleanField(default=True, verbose_name='Питательная емкость'),
        ),
        migrations.AddField(
            model_name='emkost',
            name='pump_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.pump_meter', verbose_name='Название поста'),
        ),
    ]
