# Generated by Django 4.2.14 on 2024-12-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_remove_pump_meter_emkost_emkost_pitat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tk',
            name='model_tk',
        ),
        migrations.AddField(
            model_name='emkost',
            name='model_tk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.tkmodel', verbose_name='Название Контейнера'),
        ),
        migrations.AlterField(
            model_name='emkost',
            name='pump_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.pump_meter', verbose_name='номер насоса'),
        ),
    ]
