# Generated by Django 4.2.14 on 2024-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0041_remove_tk_model_tk_emkost_model_tk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump_meter',
            options={'verbose_name': 'Насос топливный', 'verbose_name_plural': 'Насосы топливные'},
        ),
        migrations.AlterField(
            model_name='alternatormodel',
            name='power_rab_kva',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощьность Основная кВа'),
        ),
        migrations.AlterField(
            model_name='alternatormodel',
            name='power_rab_kvt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощьность Основная кВт'),
        ),
        migrations.AlterField(
            model_name='alternatormodel',
            name='power_res_kva',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощьность Резервная кВа'),
        ),
        migrations.AlterField(
            model_name='alternatormodel',
            name='power_res_kvt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощьность Резервная кВт'),
        ),
    ]
