# Generated by Django 4.2.14 on 2024-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0042_alter_pump_meter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdgu',
            name='hours',
            field=models.FloatField(blank=True, null=True, verbose_name='МотоЧасы'),
        ),
    ]
