# Generated by Django 4.2.14 on 2024-12-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0043_createdgu_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternator',
            name='hours_alternator',
            field=models.FloatField(default=0, null=True, verbose_name='Моточасы'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='hours',
            field=models.FloatField(default=0, null=True, verbose_name='МотоЧасы'),
        ),
        migrations.AlterField(
            model_name='dvs',
            name='engine_hours',
            field=models.FloatField(default=0, null=True, verbose_name='Моточасы'),
        ),
        migrations.AlterField(
            model_name='emkost',
            name='meter',
            field=models.FloatField(default=0, null=True, verbose_name='Измерения см.'),
        ),
        migrations.AlterField(
            model_name='mercury',
            name='meter',
            field=models.FloatField(default=0, null=True, verbose_name='Покозания Меркурия'),
        ),
        migrations.AlterField(
            model_name='mercury',
            name='meter1',
            field=models.FloatField(default=0, null=True, verbose_name='Покозания Меркурия короткое'),
        ),
        migrations.AlterField(
            model_name='pump_meter',
            name='meter',
            field=models.FloatField(default=0, null=True, verbose_name='Покозания счетчика насоса'),
        ),
        migrations.AlterField(
            model_name='pump_meter',
            name='meter1',
            field=models.FloatField(default=0, null=True, verbose_name='Покозания счетчика насоса короткое'),
        ),
    ]
