# Generated by Django 4.2.14 on 2024-12-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0042_alter_pump_meter_options_createdgu_engine_hours_and_more'),
        ('report', '0044_alter_alternator_hours_alternator_and_more'),
    ]

    operations = [
    ]
