# Generated by Django 4.2.14 on 2024-12-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0045_merge_20241224_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createdgu',
            old_name='tk',
            new_name='tk_nak',
        ),
        migrations.RemoveField(
            model_name='createdgu',
            name='emkost',
        ),
        migrations.RemoveField(
            model_name='createdgu',
            name='engine_hours',
        ),
        migrations.RemoveField(
            model_name='createdgu',
            name='narabotka',
        ),
        migrations.AddField(
            model_name='createdgu',
            name='emk_pit',
            field=models.BooleanField(default=True, verbose_name='Емкость питательная'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='emkost_nak',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.tk', verbose_name='Номер накопительной емкости'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='emkost_pit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.emkost', verbose_name='Номер питательной емкости'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='mrc',
            field=models.BooleanField(default=False, verbose_name='Меркурий'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='pump_m',
            field=models.BooleanField(default=True, verbose_name='Счетчик Насоса'),
        ),
        migrations.AddField(
            model_name='createdgu',
            name='pump_meter',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.pump_meter', verbose_name='Счетчик насоса'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='emkost_nak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.tk', verbose_name='Номер накопительной емкости'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='emkost_nak_pok',
            field=models.FloatField(blank=True, null=True, verbose_name='Уровень ДТ  см'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='emkost_pit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.emkost', verbose_name='Номер питательной емкости'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='emkost_pit_pok',
            field=models.FloatField(blank=True, null=True, verbose_name='Уровень ДТ  см'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='mercury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.mercury', verbose_name='Счетчик меркурий'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='mercury_pok',
            field=models.FloatField(default=0, null=True, verbose_name='Покозания Меркурия'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='pump_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.pump_meter', verbose_name='Счетчик насоса'),
        ),
        migrations.AddField(
            model_name='reportdgu',
            name='pump_meter_pok',
            field=models.FloatField(blank=True, null=True, verbose_name='Счетчик л'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='full_load',
            field=models.BooleanField(default=True, verbose_name='Полная Нагрузка'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='mercury',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.mercury', verbose_name='Счетчик меркурий'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='motochas_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Моточасы последнего ТО'),
        ),
        migrations.AlterField(
            model_name='createdgu',
            name='reactive',
            field=models.BooleanField(default=True, verbose_name='Реактивная Нагрузка'),
        ),
    ]
