# Generated by Django 4.2.14 on 2024-12-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0046_rename_tk_createdgu_tk_nak_remove_createdgu_emkost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercury',
            name='name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер Счетчика'),
        ),
    ]
